language: java
sudo: false
notifications:
  slack:
    secure: f2lylRvGcAr6C+boZ/weJ6Hvb2FcK8oE2SL9AuXaoh9pTHM6vg22IUMswroE4dj5njYoS0+N64yjWd2r+D5sE+qmcGc/3Yb6XcGxP204x06nERDhv/kVbgrwgUlLxinWJLtoAvXwHOy1zolyGa7WgmYZ4znN1tAoD1OUL51PTsv/7IUzm0SXqsP3+BlFt83snEyI/WCONgS/gxVwnh0ciUVg228pj93LREdk/iO1Zn8XqhxGGXtqVnPUJ0UidB6IzMVkpaiVPO7hCNnwIhmS7ZDNXtUFSD0JzKYrpSVhga/cXJ4NN6MtJ9g5fwERVHtQXfKV+O2nqvVO9uGOIq1s1kF4LeVT555Z+Diwpn7G4B8WqhFeW3veGU/KqzXT09rQnxmLONKlEK2zr8Bx4C8ZOx9TLW5ELO+vXJliPM7I/umaAaQWaFoCNGnsdFY/aXcp3/ASe8ob5VtO8EV29hh1daab0k9NxdHk6XwqZOT7ex4agEs0A9smGyvrjkNQ5eOJDy6U35dBHi9ilNv62c8QDlG6hgCZwIBfsucwvY31HcJvmElhzBdei2KKIaljl5UQy3RRT1C99dI+88PKOoURMI+whmQxa+0Cuek46J4opGFeSLlreP7GVtYLFxnlaA97RZYswIthlaxBMiV8zdG2k6Q22hkb2GIX1GpE5m5TyU4=
deploy:
  provider: releases
  api_key:
    secure: Rp/oWduOqQ88OWfv1wBUsrpE4G625UiqVXZm2J/Ecd0Ol9TSZcOz15yT3fz/+9/X+i48S9aXUQQ5zH3tAmYFn2xyvMxQaXFX6JSPaR6KipKBR4AxaVTofgY6pvzD6qCG9ZXy/l1YHLXBsQWkIDJo4HV/TYLUSF83N+PGBn8aO7GYHiHr1REEQt1AjT/slMSZuI1VQM/nTA0RU/m3N5BQwtJ3m5K3zvZdEEeS0RqDV9Wn+uJo2CJc8ZL/aSt6J6x8lmPrylhsLbqlY2w+0Dga+8RXXMrRGh0Q5i0PEtGaE44wC0lhvVe11Mg3WPcBx86AAnIoI18lqreyLsYtq6AcKdeP986Z86gtGdu3/tAmMrgknX4hHNt46dqa8HwyEon00f97+qADIlcoGSLiivLZ8Rg0ZZ2I1e9wUihw02WmHvxr56mS/c328vgKj9x/eo3FyuRdrZ9l2pVCRTzCgQPPe7lMqyKWzZoZ3zdTL73yLWa31r5nGnxJbN4vViZavYG4ZRV5eK8upxRhjRrUIAGFS5xOm5BQcxUQsGKUVAKw0dK7npoQZJx9kWl3ZVrq+aenWJ4Tb9LcfZHInswYhXFXyz6fLaSY6Ld8o7lWX9t61MvUPPEMvAK6AZczYuOGFqway+ERKjidHo0GS1VMGhxyxC/iEJADZe0KCbAe+SAb8eo=
  file_glob: true
  file: build/libs/xlr-msteams-plugin.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-teams-plugin