language: java
sudo: false
notifications:
  slack:
    secure: f2lylRvGcAr6C+boZ/weJ6Hvb2FcK8oE2SL9AuXaoh9pTHM6vg22IUMswroE4dj5njYoS0+N64yjWd2r+D5sE+qmcGc/3Yb6XcGxP204x06nERDhv/kVbgrwgUlLxinWJLtoAvXwHOy1zolyGa7WgmYZ4znN1tAoD1OUL51PTsv/7IUzm0SXqsP3+BlFt83snEyI/WCONgS/gxVwnh0ciUVg228pj93LREdk/iO1Zn8XqhxGGXtqVnPUJ0UidB6IzMVkpaiVPO7hCNnwIhmS7ZDNXtUFSD0JzKYrpSVhga/cXJ4NN6MtJ9g5fwERVHtQXfKV+O2nqvVO9uGOIq1s1kF4LeVT555Z+Diwpn7G4B8WqhFeW3veGU/KqzXT09rQnxmLONKlEK2zr8Bx4C8ZOx9TLW5ELO+vXJliPM7I/umaAaQWaFoCNGnsdFY/aXcp3/ASe8ob5VtO8EV29hh1daab0k9NxdHk6XwqZOT7ex4agEs0A9smGyvrjkNQ5eOJDy6U35dBHi9ilNv62c8QDlG6hgCZwIBfsucwvY31HcJvmElhzBdei2KKIaljl5UQy3RRT1C99dI+88PKOoURMI+whmQxa+0Cuek46J4opGFeSLlreP7GVtYLFxnlaA97RZYswIthlaxBMiV8zdG2k6Q22hkb2GIX1GpE5m5TyU4=
deploy:
  provider: releases
  api_key:
    secure: X/be6cfXfi6jRJyNhHB0XkJtKQZQ/8Cwkcx0XgKbXGvEQ0pyz87qh0AUgW6AMfVqqGFP9oIN8lWdBh1nveEy3RJi+4zJbgkv0LIPTbjwpODScm2IvBDqsOehhct8VDCuWJSJyRNB+haVT0zUOmyynvnHzk+1TrDtP6fp302MZx4PJsBfQHUIoEwCTy6vMkdGZLoT8+H1KcoXvnG8obhNILZnP5s7agVx/BlviON6gRuXBpSu7/KdPf4BNUL3KIAt6ym4IesvN0Iy+PchV+reBL8F6FCgs+sdCuK7JKoAdbs64rcUWkMGY0RZUDOpCgXwJuj/cGz8dDEmwBW5zagmV4HblDlWzlakOmjLNVJisX7ailcvM0yqfPZlEb+mXMgyasLC6byj+phBJroxQEmvKqYqRSvsEScZeb85S9k3kxpWygh2mmAimSncIa6Na4isJi9tumhkzQRtgNJMbKilqZqYipvQ2F8k1AVPbhk2jrRuK8Rj4KPUPOw7QW0iGOnQoxyFR5ziU9elhxsj2ihI4pMoReUk9VULOFKL5h21CLknBF5KRhDtqd2I++E91fymQHNjaGJeFjun1zTzOLAX0mUXewUI5W0KOLOPhA1QK7KOlB+9e4KS/iOVkaYJrTOf8ZvdYmDE3hmQG4B/JWrwnmvT517CXfJnLxxMt33I1ms=
  file_glob: true
  file: build/libs/xlr-msteams-plugin.jar
  skip_cleanup: true
  on:
    repo: xebialabs-community/xlr-teams-plugin
